### PR TITLE
V1.0.2

### LINKED ISSUE #26: Issues connecting Wifi on Windows
My Wifi shield has an address of 10.0.1.12 and is attached to a Ganglion board.

Able to connect and stream data using auto-detect and wifi direct on a Mac running OS X Mojave with OpenBCI_NodeJS_Wifi tests and in the Hub.

Using a Windows 10 machine, getStreamingWiFiDirect.js produces an error. This same error is happening in the current GUI when trying to connect, along with other errors stemming from a failure to connect.

```
PS C:\Users\Retiutut\Documents\GitHub\OpenBCI_NodeJS_Wifi\examples\getStreamingWiFiDirect> node getStreamingWifiDirect.js
TCP: on port:  51599
Attempting to connect to 10.0.1.12
-> POST: 10.0.1.12/tcp {"ip":"192.168.56.1","output":"raw","port":51599,"delimiter":false,"latency":16667}
server listening 192.168.56.1:62971
STATUS: 504
No more data in response.
BODY: {"connected":false,"delimiter":false,"ip":"192.168.56.1","output":"raw","port":51599,"latency":16667}
Error: ERROR: CODE: 504 MESSAGE: {"connected":false,"delimiter":false,"ip":"192.168.56.1","output":"raw","port":51599,"latency":16667}
    at IncomingMessage.res.once (C:\Users\Retiutut\Documents\GitHub\OpenBCI_NodeJS_Wifi\openBCIWifi.js:1120:16)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

### PR DESCRIPTION
**Pull request by retiutut**
- Fixes #26 

- Adds https://www.npmjs.com/package/os to check networking interfaces on Windows machines to make a fix possible

### CODE REVIEW

**Comment by daniellasry** [comment]
Code looks good! You just have some merge conflicts with master. Can you pull from master and resolve them?

```
> git fetch --all
> git merge upstream/master
```

**Comment by andrewjaykeller** [comment]
Ah sorry I didn’t mean to hit request changes!

File: openBCIWifi.js [hunk 1]
```diff
@@ -4,17 +4,19 @@ const _ = require('lodash');
 const util = require('util');
 // Local imports
 const OpenBCIUtilities = require('@openbci/utilities');
-const obciUtils = OpenBCIUtilities.utilities;
-const k = OpenBCIUtilities.constants;
-const obciDebug = OpenBCIUtilities.debug;
+const obciUtils = require('@openbci/utilities/dist/utilities');
+const k = require('@openbci/utilities/dist/constants');
+const obciDebug = OpenBCIUtilities.Debug;
```
Comment (daniellasry) [inline openBCIWifi.js]: what the reason for changing these imports? did they not work the way they were before?

code looks good otherwise, and it works for me!

Comment (retiutut) [reply openBCIWifi.js]: both work, it doesn't need to be changed
